MomentumPlus.Activate.Web/Areas/Home/Models/WidgetsViewModel.cs
using MomentumPlus.Core.Models;
using System;

namespace MomentumPlus.Activate.Web.Areas.Home.Models
{
    public class WidgetsViewModel
    {
        public Guid PackageId { get; set; }

        public string Test  { get; set; }



        public Package.Widget? Widget1 { get; set; }
        public Package.Widget? Widget2 { get; set; }
        public Package.Widget? Widget3 { get; set; }
    }
}

MomentumPlus.Activate.Web/Areas/Home/Controllers/WidgetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using MomentumPlus.Activate.Services.Interfaces;
using MomentumPlus.Activate.Web.Areas.Home.Models;
using MomentumPlus.Activate.Web.Controllers;
using MomentumPlus.Activate.Web.Core;
using MomentumPlus.Activate.Web.Helpers;
using MomentumPlus.Activate.Web.Models;
using MomentumPlus.Core.Models;
using MomentumPlus.Core.Models.People;

namespace MomentumPlus.Activate.Web.Areas.Home.Controllers
{
    public class WidgetsController : BaseController
    {
        private readonly IAttachmentService AttachmentService;
        private readonly IContactService ContactService;
        private readonly IDocumentLibraryService DocumentLibraryService;
        private readonly ProjectCore ProjectCore;
        private readonly IProjectService ProjectService;

        public WidgetsController(
            IAttachmentService attachmentService,
            IAuditService auditService,
            IContactService contactService,
            IDocumentLibraryService documentLibraryService,
            IImageService imageService,
            IMasterListService masterListService,
            IModerationService moderationService,
            IPackageService packageService,
            IProjectService projectService,
            IRequestService requestService,
            IUserService userService,
            ProjectCore projectCore)
            : base(
                auditService,
                masterListService,
                packageService,
                userService
                )
        {
            AttachmentService = attachmentService;
            ContactService = contactService;
            DocumentLibraryService = documentLibraryService;
            ProjectService = projectService;

            ProjectCore = projectCore;
        }

        [ChildActionOnly]
        public ActionResult MyAttachments(WidgetViewModel viewModel)
        {
            var attachments = AttachmentService.GetRecentByPackage(viewModel.PackageId);
            var documents = DocumentLibraryService.GetRecentByPackageId(viewModel.PackageId);

            viewModel.Attachments = attachments.Concat(documents).OrderByDescending(m => m.Created).Take(9);

            ViewData["CurrentPackage"] = GetCurrentPackage();

            return View(viewModel);
        }

        [ChildActionOnly]
        public ActionResult MyTeam(WidgetViewModel viewModel)
        {
            viewModel.StaffContacts = ContactService.GetTeamContacts(viewModel.PackageId, Person.SortColumn.FirstName);
            viewModel.DefaultCompanyId = MasterListService.GetDefaultCompanyId();
            viewModel.ShowGoToPackage = AppSession.Current.CurrentUser.Role != null &&
                                        (AppSession.Current.CurrentUser.Role.RoleParsed == Role.RoleEnum.LineManager ||
                                         AppSession.Current.CurrentUser.Role.RoleParsed == Role.RoleEnum.HRManager ||
                                         AppSession.Current.CurrentUser.Role.RoleParsed == Role.RoleEnum.Administrator ||
                                         AppSession.Current.CurrentUser.Role.RoleParsed == Role.RoleEnum.iHandoverAgent ||
                                         AppSession.Current.CurrentUser.Role.RoleParsed == Role.RoleEnum.iHandoverAdmin);
            return View(viewModel);
        }

        [ChildActionOnly]
        public ActionResult MyProjects(WidgetViewModel viewModel)
        {
            var projectInstances = ProjectService.GetProjectInstances(viewModel.PackageId, null,
                ProjectInstance.SortColumn.Name, true, approved: null);
            viewModel.ProjectInstances = Mapper.Map<IEnumerable<ProjectInstance>,
                IEnumerable<ProjectInstanceViewModel>>(projectInstances);

            foreach (var project in viewModel.ProjectInstances)
            {
                if (project.ProjectId == null && project.NewProjectRequest != null)
                {
                    project.Project = ProjectCore.GetDummyProjectViewModel(project.NewProjectRequest.SuggestedName,
                        project.NewProjectRequest.SuggetestedProjectId);
                }

                if (project.Package.AncestorPackageId.HasValue && project.ProjectId.HasValue)
                {
                    var projectInstance = ProjectService.GetProjectInstanceByPackageAndProjectId(project.Package.AncestorPackageId.Value, project.ProjectId.Value);
                    if (projectInstance != null)
                        project.FirstTask = projectInstance.Tasks.OrderBy(t => t.Fixed).Any() && projectInstance != null ?  projectInstance.Tasks.OrderBy(t => t.Fixed).FirstOrDefault() : null;
                }
            }

            return View(viewModel);
        }

        /// <summary>
        /// Update the widget at the given position to the given type.
        /// </summary>
        /// <param name="packageId"></param>
        /// <param name="widgetNumber"></param>
        /// <param name="widgetType"></param>
        /// <returns></returns>
        public bool UpdateWidget(Guid packageId, int widgetPosition, Package.Widget widgetType)
        {
            try
            {
                var package = PackageService.GetByPackageId(packageId);

                switch (widgetPosition)
                {
                    case 1:
                        package.Widget1 = widgetType;
                        break;
                    case 2:
                        package.Widget2 = widgetType;
                        break;
                    case 3:
                        package.Widget3 = widgetType;
                        break;
                }

                PackageService.Update(package);
                return true;
            }
            catch (Exception ex)
            {
                LogException(ex);
                return false;
            }
        }

        /// <summary>
        ///     Remove the widget at the given position on the given package.
        /// </summary>
        /// <param name="packageId"></param>
        /// <param name="widgetPosition"></param>
        /// <returns></returns>
        public bool RemoveWidget(Guid packageId, int widgetPosition)
        {
            try
            {
                var package = PackageService.GetByPackageId(packageId);

                switch (widgetPosition)
                {
                    case 1:
                        package.Widget1 = null;
                        break;
                    case 2:
                        package.Widget2 = null;
                        break;
                    case 3:
                        package.Widget3 = null;
                        break;
                }

                PackageService.Update(package);
                return true;
            }
            catch (Exception ex)
            {
                LogException(ex);
                return false;
            }
        }
    }
}

MomentumPlus.Activate.Web/Controllers/AttachmentsController.cs
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MomentumPlus.Activate.Services;
using MomentumPlus.Activate.Services.Interfaces;
using MomentumPlus.Activate.Web.Attributes;
using MomentumPlus.Activate.Web.Core;
using MomentumPlus.Activate.Web.Extensions;
using MomentumPlus.Activate.Web.Helpers;
using MomentumPlus.Activate.Web.Models;
using MomentumPlus.Core.Models;

namespace MomentumPlus.Activate.Web.Controllers
{
    /// <summary>
    /// Controller for attachment management for all entities
    /// that can have attachments.
    /// </summary>
    public class AttachmentsController : BaseController
    {
        private AttachmentCore AttachmentCore;
        private DocumentLibraryCore DocumentLibraryCore;

        #region IOC

        private IAttachmentService AttachmentService;
        private IFileService FileService;

        /// <summary>
        /// Construct a new <c>TopicController</c> with the given service
        /// implementations.
        /// </summary>
        public AttachmentsController(
            IAttachmentService attachmentService,
            IAuditService auditService,
            IContactService contactService,
            IDocumentLibraryService documentLibraryService,
            IFileService fileService,
            IMasterListService masterListService,
            IMeetingService meetingService,
            IPackageService packageService,
            IPeopleService peopleService,
            IProjectService projectService,
            IPositionService positionService,
            ITaskService taskService,
            ITopicService topicService,
            IHandoverService handoverService,
            IUserService userService,
            AttachmentCore attachmentCore,
            DocumentLibraryCore documentLibraryCore
        ) : base(
            auditService,
            masterListService,
            packageService,
            userService)
        {
            AttachmentCore = attachmentCore;

            DocumentLibraryCore = documentLibraryCore;

            AttachmentService = attachmentService;
            FileService = fileService;
        }

        #endregion

        #region ACTIONS

        #region Index

        /// <summary>
        /// Render the attachment manager view for the given item.
        /// </summary>
        /// <param name="id">The ID of the item.</param>
        /// <param name="type">The <c>ItemType</c> corresponding to the item.</param>
        [Authorise("Attachment")]
        [HttpGet]
        public ActionResult Index(Guid id, ItemType type)
        {;
            var attachments = AttachmentCore.GetAttachmentsViewModel(id, type, GetCurrentPackage());

            AppSession.Current.AttachmentFormReturnUrl = Request.RawUrl;
            AppSession.Current.DocumentLibraryReturnUrl = Request.RawUrl;

            return View(attachments);
        }

        #endregion

        #region Create

        /// <summary>
        /// Render the attachment form in create mode.
        /// </summary>
        /// <param name="id">The ID of item to add an attachment to.</param>
        /// <param name="type">The <c>ItemType</c> corresponding to the item.</param>
        [Authorise("Attachment")]
        [HttpGet]
        public ActionResult Create(Guid id, ItemType type)
        {
            AttachmentViewModel viewModel = new AttachmentViewModel
            {
                ItemId = id,
                ItemType = type,
                FileTypes = AttachmentHelper.AllowedFileTypes,
                ChooseFileUpload = true
            };

            return View("AttachmentForm", viewModel);
        }

        /// <summary>
        /// Handle create attachment form submission.
        /// </summary>
        /// <param name="attachmentViewModel">The model containing the submitted form data.</param>
        /// <param name="theFile">The uploaded file.</param>
        [Authorise("Attachment")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AttachmentViewModel attachmentViewModel, HttpPostedFileBase theFile)
        {
            attachmentViewModel.FileTypes = AttachmentHelper.AllowedFileTypes.ConvertAll(f => f.ToLower());

            // Ensure that either a file or file location was entered
            if (theFile == null && string.IsNullOrWhiteSpace(attachmentViewModel.FilePath))
            {
                var errorMessage = "You must select a file to upload or specify a file location.";
                ModelState.AddModelError("PostedFile", errorMessage);
                ModelState.AddModelError("FilePath", errorMessage);
            }
            else if (theFile != null && !attachmentViewModel.FileTypes.Contains(theFile.FileName.Substring(theFile.FileName.LastIndexOf(".")).ToLower()))
            {
                // Check the file type is valid
                ModelState.AddModelError("PostedFile", @"This file type is not supported.");
            }

            if (attachmentViewModel.FilePath != null)
            {
                // Check for invalid characters in file path
                var invalidChars = Path.GetInvalidPathChars();
                var invalidCharsFound = false;
                foreach (var character in attachmentViewModel.FilePath.Where(character => invalidChars.Contains(character)))
                {
                    invalidCharsFound = true;
                }
                if (invalidCharsFound)
                {
                    ModelState.AddModelError("FilePath", @"Please enter a file path that does not contain illegal characters.");
                }
            }
            
            if (!ModelState.IsValid)
            {
                return View("AttachmentForm", attachmentViewModel);
            }

            try
            {
                AttachmentCore.CreateAttachment(attachmentViewModel, theFile);
                AddAlert(AlertViewModel.AlertType.Success, "Added successfully.");
            }
            catch (Exception ex)
            {
                LogException(ex);
                AddAlert(AlertViewModel.AlertType.Danger, "Error adding attachment.");
            }

            return Redirect(AppSession.Current.AttachmentFormReturnUrl);
        }

        #endregion

        #region Edit

        /// <summary>
        /// Render the attachment form in edit mode.
        /// </summary>
        /// <param name="id">The ID of item attachment.</param>
        /// <param name="itemId">The ID of item to add an attachment to.</param>
        /// <param name="type">The <c>ItemType</c> corresponding to the item.</param>
        [Authorise("AttachmentEdit")]
        [HttpGet]
        public ActionResult Edit(Guid id, Guid itemId, ItemType type)
        {
            var viewModel = AttachmentCore.GetAttachmentViewModel(id, itemId, type);
            return View("AttachmentForm", viewModel);
        }

        /// <summary>
        /// Handle edit attachment form submission.
        /// </summary>
        /// <param name="attachmentViewModel">The model containing the submitted form data.</param>
        [Authorise("AttachmentEdit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AttachmentViewModel attachmentViewModel, HttpPostedFileBase theFile)
        {
            Attachment attachment = AttachmentService.GetByID(attachmentViewModel.ID);
            attachmentViewModel.FileTypes = AttachmentHelper.AllowedFileTypes;

            // Ensure that either a file or file location was entered
            if (theFile == null && !attachmentViewModel.FileId.HasValue && string.IsNullOrWhiteSpace(attachmentViewModel.FilePath))
            {
                var errorMessage = "You must select a file to upload or specify a file location.";
                ModelState.AddModelError("PostedFile", errorMessage);
                ModelState.AddModelError("FilePath", errorMessage);
            }
            else if (theFile != null && !theFile.IsValid())
            {
                ModelState.AddModelError("PostedFile", "This file type is not supported.");
            }

            if (!ModelState.IsValid)
            {
                return View("AttachmentForm", attachmentViewModel);
            }

            try
            {
                AttachmentCore.UpdateAttachment(attachment, attachmentViewModel, theFile);
                AddAlert(AlertViewModel.AlertType.Success, "Updated successfully.");
            }
            catch (Exception ex)
            {
                LogException(ex);
                AddAlert(AlertViewModel.AlertType.Danger, "Error editing attachment.");
            }

            return Redirect(AppSession.Current.AttachmentFormReturnUrl);
        }

        #endregion

        #region Download

        /// <summary>
        /// Download an attachment.
        /// </summary>
        /// <param name="id">The attachment ID.</param>
        [HttpGet]
        public ActionResult Download(Guid id)
        {
            var attachment = AttachmentService.GetByID(id);

            // If the attachment was linked from the document library then return the source attachment
            if (attachment.InLibrary && attachment.SourceId.HasValue)
            {
                attachment = AttachmentService.GetByID(attachment.SourceId.Value);
            }

            var file = FileService.GetFile(attachment.FileId.Value);
            return File(file.BinaryData, MimeTypeMap.GetMimeType(file.FileType), attachment.FileName);
        }

        #endregion

        #region RetireAttachment/ResumeAttachment

        /// <summary>
        /// Retire an attachment
        /// </summary>
        /// <param name="id">The attachment GUID</param>
        /// <param name="itemId">The attachment parent ID</param>
        /// <param name="type">Attachment parent type</param>
        /// <returns></returns>
        [Authorise("AttachmentEdit")]
        [HttpGet]

MomentumPlus.Activate.Web/Areas/Home/Views/Widgets/Attachment.cshtml
@using MomentumPlus.Activate.Web.Extensions
@using MomentumPlus.Activate.Web.Helpers
@model MomentumPlus.Core.Models.BaseModel

@{
    MomentumPlus.Core.Models.Attachment attachment = null;

    var empty = new HtmlString("<br>");

    var isAttachment = Model is MomentumPlus.Core.Models.Attachment;
    var isDocument = Model is MomentumPlus.Core.Models.DocumentLibrary;

    string parentTitle = null;
    string fileExtension;

    string editUrl = null;
    string parentEditUrl = null;
    string downloadUrl;

    var uploaded = default(DateTime);

    MomentumPlus.Core.Models.Task task = null;
    MomentumPlus.Core.Models.Topic topic = null;
    MomentumPlus.Core.Models.Contact contact = null;
    //MomentumPlus.Activate.Entities.Models.People.Staff staff = null;
    MomentumPlus.Core.Models.Meeting meeting = null;
    MomentumPlus.Core.Models.ProjectInstance projectInstance = null;

    if (isAttachment)
    {
        attachment = Model as MomentumPlus.Core.Models.Attachment;
        uploaded = attachment.Created.Value;
        task = attachment.ParentTask;
        topic = attachment.ParentTopic;
        contact = attachment.Contact;
        //staff = attachment.Staff;
        meeting = attachment.Meeting;
        projectInstance = attachment.ProjectInstance;
    }
    else if (isDocument)
    {
        var document = Model as MomentumPlus.Core.Models.DocumentLibrary;
        attachment = document.Attachment;
        uploaded = document.Created.Value;

        var package = ViewData["CurrentPackage"] as MomentumPlus.Core.Models.Package;

        task =
            document.Tasks.FirstOrDefault(
                ta =>
                    (ta.ParentTopic != null &&
                    ta.ParentTopic.ParentTopicGroup.ParentModule.Package != null &&
                    ta.ParentTopic.ParentTopicGroup.ParentModule.Package.ID == package.ID) ||
                    ta.ProjectInstace != null &&
                    ta.ProjectInstace.PackageId == package.ID);
        topic =
            document.Topics.FirstOrDefault(
                to =>
                    to.ParentTopicGroup.ParentModule.Package != null &&
                    to.ParentTopicGroup.ParentModule.Package.ID == package.ID);
        contact = document.Contacts.FirstOrDefault(c => c.PackageId == package.ID);
        meeting = document.Meetings.FirstOrDefault(m => m.ParentContact.PackageId == package.ID);
        projectInstance = document.ProjectInstances.FirstOrDefault(p => p.PackageId == package.ID);

        var staffContact =
            package.Contacts
                .Where(c => c.Managed)
                .FirstOrDefault(c => c.DocumentLibraries.Contains(document));
        //staff = staffContact;
    }

    if (task != null)
    {
        editUrl = Url.Action("Edit", "Attachments",
            new { area = "", id = attachment.ID, itemId = task.ID, type = MomentumPlus.Activate.Web.Models.ItemType.Task });
        parentTitle = task.Name;
        parentEditUrl = Url.Action("EditTask", "Task", new { area = "", id = task.ID });
    }
    else if (topic != null)
    {
        editUrl = Url.Action("Edit", "Attachments",
            new { area = "", id = attachment.ID, itemId = topic.ID, type = MomentumPlus.Activate.Web.Models.ItemType.Topic });
        parentTitle = topic.Name;
        parentEditUrl = Url.Action("EditTopic", "Topic", new { area = "", id = topic.ID });
    }
    else if (contact != null)
    {
        editUrl = Url.Action("Edit", "Attachments",
            new { area = "", id = attachment.ID, itemId = contact.ID, type = MomentumPlus.Activate.Web.Models.ItemType.Contact });
        parentTitle = contact.Name;
        parentEditUrl = Url.Action("Edit", "Relationships", new { id = contact.ID });
    }
    //else if (staff != null)
    //{
    //    editUrl = Url.Action("Edit", "Attachments",
    //        new { area = "", id = attachment.ID, itemId = staff.ID, type = MomentumPlus.Activate.Web.Models.ItemType.Staff });
    //    parentTitle = staff.FullName;
    //    parentEditUrl = Url.Action("EditPerson", "People", new { id = staff.ID });
    //}
    else if (meeting != null)
    {
        editUrl = Url.Action("Edit", "Attachments",
            new { area = "", id = attachment.ID, itemId = meeting.ID, type = MomentumPlus.Activate.Web.Models.ItemType.Meeting });
        parentTitle = meeting.Name;
        parentEditUrl = Url.Action("EditMeeting", "Relationships", new { id = meeting.ID });
    }
    else if (projectInstance != null && projectInstance.Project != null)
    {
        editUrl = Url.Action("Edit", "Attachments",
            new
            {
                area = "",
                id = attachment.ID,
                itemId = projectInstance.ID,
                type = MomentumPlus.Activate.Web.Models.ItemType.ProjectInstance
            });
        parentTitle = projectInstance.Project.Name;
        parentEditUrl = Url.Action("EditProjectCard", "Projects", new { id = projectInstance.ID });
    }

    var isUpload = attachment.FileId.HasValue;

    if (isUpload)
    {
        downloadUrl = Url.Action("Download", "Attachments", new { area = "", id = attachment.ID });
        fileExtension = Path.GetExtension(attachment.FileName);
    }
    else
    {
        downloadUrl = attachment.FilePath;
        fileExtension = Path.GetExtension(attachment.FilePath);
    }

    if (!string.IsNullOrEmpty(fileExtension))
    {
        fileExtension = fileExtension.Substring(1);
    }
}

<div class="widget-tile" data-soft-link="@parentEditUrl">
    <div class="row">
        <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5">
            <div class="attachment-icon">
                @if (AppSettings.AudioFileTypes.Contains(fileExtension))
                {
                    <span class="glyphicon glyphicon-volume-up" style="padding-top: 20px;"></span>
                }
                else if (AppSettings.DocumentFileTypes.Contains(fileExtension))
                {
                    <span class="glyphicon glyphicon-file" style="padding-top: 20px;"></span>
                }
                else if (AppSettings.ImageFileTypes.Contains(fileExtension))
                {
                    <span class="glyphicon glyphicon-picture" style="padding-top: 20px;"></span>
                }
                else
                {
                    <span class="glyphicon glyphicon-file" style="padding-top: 20px;"></span>
                }
            </div>
        </div>
        <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7">
            <div class="row">
                <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
                    <div class="string-truncate">
                        <a href="@editUrl" class="no-underline">
                            <span class="widget-body-title">
                                <strong>@attachment.Name</strong>
                            </span>
                        </a>
                    </div>

                    @if (isUpload)
                        {
                            <div class="small-text">
                                @Html.TruncateWithTooltip(attachment.FileName, 18, "bottom")
                            </div>
                            <div class="small-text">
                                <small>@Html.ReadableFileSize(attachment.Data.BinaryData.LongLength)</small>
                            </div>
                        }
                        else
                        {
                            <div>
                                @*<em>@Html.TruncatedLink(downloadUrl)</em>*@
                                @empty
                               @empty
                            </div>
                        }

                    <div style="padding-top: 20px;">
                        <small>
                            uploaded @uploaded.ToString("dd MMM yyyy")
                        </small>
                    </div>

                    <div>
                        <small style="font-size: 11px;">In @parentTitle @(isAttachment ? "(Package)" : "(Framework)")</small>
                        </div>

                        @*<div>
                            <small>
                                @(isAttachment ? "(Package)" : "(Framework)")
                            </small>
                        </div>*@
                </div>
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                    @if (isAttachment)
                    {
                        <p>
                            <a href="@editUrl">
                                <span class="edit-atachement-icon"></span>
                            </a>
                        </p>
                    }

                    <p>
                        <a href="@downloadUrl" target="_blank">
                            @if (isUpload)
                            {
                                <span class="download-atachement-icon"></span>
                            }
                            @*else
                            {
                                <span class="atachement-link" title="Link"></span>
                            }*@
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

MomentumPlus.Activate.Web/Areas/Home/Views/Widgets/MyProjects.cshtml
@model MomentumPlus.Activate.Web.Areas.Home.Models.WidgetViewModel

@{
    Layout = "~/Areas/Home/Views/Widgets/_Widget.cshtml";
}

@if (Model.ProjectInstances.Any())
{

    <div class="panel panel-default project-widget widget-panel" data-type="@Model.PackageId-MyProjects">
        <div class="panel-body">
            <ul class="widget-slider">
                @foreach (var projectInstance in Model.ProjectInstances.ToList())
                {
                    <li class="widget-slide project-slide"
                        data-attachments-count="@(projectInstance.AttachmentsCount + projectInstance.DocumentLibrariesCount)"
                        data-voicemessages-count="@projectInstance.VoiceMessagesCount"
                        data-attachments-url="@Url.Action("Index", "Attachments", new {area = "", id = projectInstance.ID, type = MomentumPlus.Activate.Web.Models.ItemType.ProjectInstance})"
                        data-voicemessages-url="@Url.Action("Index", "VoiceMessage", new {area = "", id = projectInstance.ID, type = MomentumPlus.Activate.Web.Models.ItemType.ProjectInstance})">
                        @Html.Partial("ProjectInstance", projectInstance)
                    </li>
                }
            </ul>
        </div>
        <div class="panel-footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 vertical-align">
                        <div class="widget-footer">
                            <a href="javascript:void(0);" class="attachments-link vertical-align">
                                <span class="attachments-icon  text-white"></span>
                                <span class="attachments-count text-white">0</span>
                            </a>
                            <a href="javascript:void(0);" class="voicemessages-link vertical-align">
                                <span class="voice-Messages-icon text-white"></span>
                                <span class="voicemessages-count text-white">0</span>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 text-right">
                        <ul class="pagination pagination-sm vertical-align">
                            <li>
                                <a href="#" class="prev-arrow widget-prev" aria-label="Previous">
                                    <span aria-hidden="true" class="left-Arrow-Slider-icon"></span>
                                </a>
                            </li>
                            <li>
                                <span class="widget-paginator">
                                    <span class="current-slide">@Model.Index</span>
                                    /
                                    <span>@Model.ProjectInstances.Count()</span>
                                </span>
                            </li>
                            <li class="vertical-align">
                                <a href="#" class="next-arrow widget-next" aria-label="Next">
                                    <span aria-hidden="true" class="right-Arrow-Slider-icon"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
else
{
  <div class="widget-body" style="display: table; overflow: hidden; width: 100%;margin-bottom: 10px;">
    <span class="text-center" style="display: table-cell; vertical-align: middle;"><b>You have not added any projects.</b></span>
  </div>
  <div class="panel-footer" style="height: 36px;">
  </div>
}

MomentumPlus.Activate.Web/Areas/Home/Views/Widgets/_Widget.cshtml
@using MomentumPlus.Activate.Web.Extensions
@model MomentumPlus.Activate.Web.Areas.Home.Models.WidgetViewModel

<div class="panel panel-primary widget-container">
    <div class="panel-heading no-redirect widget-panel">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
                    <h3 class="panel-title">
                        @Model.WidgetType.GetDescription()
                    </h3>
                </div>
                <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 text-right">
                    <a href="#" title="Remove" class="close-widget-button pull-right remove-widget"
                       data-package-id="@Model.PackageId" data-widget-position="@Model.WidgetPosition">
                        @*<span class="close-widget-button" aria-hidden="true"></span>*@
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body widget-body">
        @RenderBody()
    </div>
</div>