MomentumPlus.Activate.Web/Areas/Admin/Controllers/ProjectIconsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using MomentumPlus.Activate.Services.Interfaces;
using MomentumPlus.Activate.Web.Controllers;
using MomentumPlus.Activate.Web.Models;
using ImageViewModel = MomentumPlus.Activate.Web.Areas.Admin.Models.ImageViewModel;
using MomentumPlus.Core.Models;

namespace MomentumPlus.Activate.Web.Areas.Admin.Controllers
{
    public class ProjectIconsController : BaseController
    {

        private readonly IImageService ImageService;
        private readonly IFileService FileService;

        public ProjectIconsController(
            IImageService imageService, 
            IFileService fileService, 
            IAuditService auditService,
            IMasterListService masterListService,
            IPackageService packageService,
            IUserService userService) : base(
                    auditService,
                    masterListService,
                    packageService,
                    userService
                )
        {
            ImageService = imageService;
            FileService = fileService;
        }

        /// <summary>
        /// Render the project icon index view
        /// </summary>
        /// <param name="retired">
        /// If true will show retired icons only
        /// </param>
        /// <returns>The index view</returns>
        public ActionResult Index(bool retired = false)
        {
            IEnumerable<Image> images = ImageService.GetDefaultImages(retired).OrderBy(i => i.Title);

            ViewBag.Retired = retired;

            return View(images);
        }

        /// <summary>
        /// Render project icon create form
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        /// <summary>
        /// Handle project icon create form submission
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(ImageViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // Read uploaded image into memory and create new image entity
            Image newImage = null;
            using (MemoryStream memoryStream = new MemoryStream())
            {
                model.UploadedImage.InputStream.CopyTo(memoryStream);

                newImage = new Image();
                newImage.BinaryData = memoryStream.ToArray();
                newImage.FileType = Path.GetExtension(model.UploadedImage.FileName);
                newImage.ContentType = model.UploadedImage.ContentType;

                newImage.Title = model.Title;
                newImage.IsDefault = true;
            }

            // Insert the image into the database and alert user
            FileService.AddFile(newImage);

            AddAlert(AlertViewModel.AlertType.Success, "Image added sucessfully.");

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Render project icon edit form for the icon with the
        /// given ID.
        /// </summary>
        /// <param name="id">The project icon GUID</param>
        /// <returns>The project edit form view</returns>
        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            var image = ImageService.GetImage(id);

            if (image == null)
            {
                return HttpNotFound();
            }

            var model = new ImageViewModel()
            {
                Title = image.Title,
                Src = image.ToString(),
                Id = image.ID,
                Retired = image.Deleted.HasValue
            };

            return View(model);
        }

        /// <summary>
        /// Handle submission of project icon form
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ImageViewModel model)
        {
            ModelState.Remove("UploadedImage");
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // Get project icon from the database
            Image image = ImageService.GetImage(model.Id);
            image.Title = model.Title;

            if (model.UploadedImage != null)
            {
                // Read uploaded image into memory and update the entity
                using (MemoryStream memoryStream = new MemoryStream())
                {
                    model.UploadedImage.InputStream.CopyTo(memoryStream);

                    image.BinaryData = memoryStream.ToArray();
                    image.FileType = Path.GetExtension(model.UploadedImage.FileName);
                    image.ContentType = model.UploadedImage.ContentType;
                }
            }

            // Update image in the database and show success alert to user
            FileService.Update(image);
           
            AddAlert(AlertViewModel.AlertType.Success, "Image saved sucessfully.");

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Retire the project icon with the given ID
        /// </summary>
        /// <param name="id">The project icon GUID</param>
        /// <returns>A redirect to the Index action</returns>
        public ActionResult Retire(Guid id)
        {
            // Get project icon from the database
            var image = ImageService.GetImage(id);

            if (image == null)
            {
                return HttpNotFound();
            }

            // Mark as deleted and alert user
            image.Deleted = DateTime.Now;

            FileService.Update(image);

            AddAlert(AlertViewModel.AlertType.Success, "Image retired sucessfully.");

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Resume the project icon with the given ID
        /// </summary>
        /// <param name="id">The project icon GUID</param>
        /// <returns>A redirect to the Index action</returns>
        public ActionResult Resume(Guid id)
        {
            // Get project icon from the database
            var image = ImageService.GetImage(id);

            if (image == null)
            {
                return HttpNotFound();
            }

            // Undelete and alert user
            image.Deleted = null;

            FileService.Update(image);

            AddAlert(AlertViewModel.AlertType.Success, "Image resumed sucessfully.");

            return RedirectToAction("Index");
        }

    }
}

MomentumPlus.Activate.Web/Areas/Admin/Views/ProjectIcons/Add.cshtml
@model MomentumPlus.Activate.Web.Areas.Admin.Models.ImageViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Add", "ProjectIcons", FormMethod.Post,
        new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    

    <div class="panel panel-secondary">
        <div class="panel-heading display-table">
            <div class="vertical-cell">
                Add Project Icon
            </div>
        </div>
        <div class="panel-body">
            @Html.ValidationSummary()

            <div class="form-group">
                <div class="col-sm-2 control-label">
                    @Html.LabelFor(m => m.Title)
                </div>
                <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Title)
                </div>
            </div>

            <div class="form-group">
                @*<div class="col-sm-2 control-label">
                    @Html.LabelFor(m => m.UploadedImage)
                </div>*@
                <div class="col-sm-offset-2 col-sm-10">
                    <input class="form-control" type="file" name="@Html.NameFor(m => m.UploadedImage)" id="@Html.IdFor(m => m.UploadedImage)" />
                    <small><em>Image must be .png, .jpeg</em></small>
                    @Html.ValidationMessageFor(m => m.UploadedImage)
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <div class="text-right">
                <button class="btn btn-primary" type="submit">Add</button>
                <a class="btn btn-danger" href="@Url.Action("Index")">Close</a>
            </div>
        </div>
    </div>
}

MomentumPlus.Activate.Web/Areas/Admin/Views/ProjectIcons/Edit.cshtml
@model MomentumPlus.Activate.Web.Areas.Admin.Models.ImageViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Edit", "ProjectIcons", FormMethod.Post,
        new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.Src)
    @Html.HiddenFor(m => m.Retired)

    <div class="panel panel-secondary">
        <div class="panel-heading display-table">
            <div class="vertical-cell">
                Add Project Icon
            </div>
        </div>
        <div class="panel-body">
            @Html.ValidationSummary()

            <div class="form-group">
                <div class="col-sm-2 control-label">
                    @Html.LabelFor(m => m.Title)
                </div>
                <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Title)
                </div>
            </div>

            <div class="form-group">
                @*<div class="col-sm-2 control-label">
                        @Html.LabelFor(m => m.UploadedImage)
                    </div>*@
                <div class="col-sm-offset-2 col-sm-10">
                    <input class="form-control" type="file" name="@Html.NameFor(m => m.UploadedImage)" id="@Html.IdFor(m => m.UploadedImage)" />
                    <small><em>Image must be .png, .jpeg</em></small>
                    @Html.ValidationMessageFor(m => m.UploadedImage)

                    <div class="margin-top">
                        <p>Upload new image to replace current</p>
                        <img class="current-project-image" src="@Model.Src" title="@Model.Title"/>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer display-table">
            <div class="vertical-cell">
                <a class="btn btn-danger" @(Model.Retired ? "disabled" : null) href="@Url.Action("Retire", new { id = Model.Id })">Retire</a>
                <a class="btn btn-primary" @(!Model.Retired ? "disabled" : null) href="@Url.Action("Resume", new { id = Model.Id })">Resume</a>
            </div>
            <div class="vertical-cell text-right">
                <button class="btn btn-primary" type="submit">Add</button>
                <a class="btn btn-danger" href="@Url.Action("Index")">Close</a>
            </div>
        </div>
    </div>
}

MomentumPlus.Activate.Web/Areas/Admin/Views/ProjectIcons/Index.cshtml
@model IEnumerable<MomentumPlus.Core.Models.Image>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ul class="nav nav-pills">
    <li role="presentation" class="@(!ViewBag.Retired ? "active" : null)"><a href="@Url.Action("Index")">Active</a></li>
    <li role="presentation" class="@(ViewBag.Retired ? "active" : null)"><a href="@Url.Action("Index", new { retired = true })">Retired</a></li>
</ul>

@*<ul>
    @foreach (var image in Model)
    {
        <li><a href="@Url.Action("Edit", new {id = image.ID})">@image.Title</a></li>
    }
</ul>*@

@helper AddButton() {
    if (!ViewBag.Retired)
    {
        <div class="vertical-cell text-right">
            @Html.ActionLink("Add", "Add", null, new {@class = "btn btn-primary"})
        </div>
    }
}

<div class="panel panel-secondary margin-top">
    <div class="panel-heading no-redirect display-table">
        <div class="vertical-cell">
            Project Icons
        </div>
        @*@AddButton()*@
    </div>
    <div class="panel-body">
        <div class="list-group project-images">
            @foreach (var image in Model)
            {
                <a href="@Url.Action("Edit", new {id = image.ID})" class="list-group-item"><img src="@image" title="@image.Title" alt="@image.Title"/> <h4>@image.Title</h4></a>
            }
        </div>
    </div>
    <div class="panel-footer display-table">
        @AddButton()
    </div>
</div>